name: CI

on:
   push:
      branches: [release]
   pull_request:
      branches: [release]

jobs:
   firebase-deploy:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@master
           with:
              node-version: '12.x'

         - name: Install npm dependencies
           run: npm install

         - name: Build project
           run: npm run build

         - uses: w9jds/firebase-action@master
           name: Deploy to Firebase
           with:
              args: deploy --only hosting
           env:
              FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
